/**
 * Default categories: canonical English `name` (the stable identifier stored in
 * the database and referenced by demo data and categorisation), the i18n key the
 * UI renders instead, and the multilingual keywords auto-categorisation matches
 * against.
 *
 * `name` is deliberately not localised. It is a row identity, so translating it
 * would rewrite user data every time the language changed. `translationKey`
 * points at `categories.*` in the locale files; `categoryLabel()` resolves it.
 *
 * Data only — no database import — so both the seeder and the label helper can
 * read it without pulling in the SQLite client.
 */
export const DEFAULT_CATEGORIES = [
  {
    name: 'Produce',
    translationKey: 'produce',
    icon: '🥬',
    color: '#93BD57',
    keywords: [
      'apple',
      'banana',
      'orange',
      'lettuce',
      'tomato',
      'carrot',
      'onion',
      'potato',
      'fruit',
      'vegetable',
      'organic',
      'avocado',
      'lemon',
      'lime',
      'grape',
      'berry',
      'melon',
      'cucumber',
      'pepper',
      'broccoli',
      'spinach',
      'kale',
      'celery',
      'garlic',
      'manzana',
      'platano',
      'naranja',
      'lechuga',
      'tomate',
      'zanahoria',
      'cebolla',
      'papa',
      'patata',
      'fruta',
      'verdura',
      'aguacate',
      'limon',
      'uva',
      'fresa',
      'melon',
      'sandia',
      'pepino',
      'pimiento',
      'brocoli',
      'espinaca',
      'apio',
      'ajo',
    ],
    isDefault: true,
  },
  {
    name: 'Dairy',
    translationKey: 'dairy',
    icon: '🥛',
    color: '#5BA4D9',
    keywords: [
      'milk',
      'cheese',
      'yogurt',
      'butter',
      'cream',
      'egg',
      'eggs',
      'sour cream',
      'cottage',
      'mozzarella',
      'cheddar',
      'parmesan',
      'dairy',
      'half and half',
      'leche',
      'queso',
      'yogur',
      'mantequilla',
      'crema',
      'huevo',
      'huevos',
      'nata',
      'requeson',
      'lacteo',
      'lacteos',
      'quesillo',
      'queso fresco',
    ],
    isDefault: true,
  },
  {
    name: 'Meat',
    translationKey: 'meat',
    icon: '🥩',
    color: '#980404',
    keywords: [
      'beef',
      'chicken',
      'pork',
      'turkey',
      'fish',
      'salmon',
      'steak',
      'ground',
      'bacon',
      'sausage',
      'ham',
      'lamb',
      'shrimp',
      'tuna',
      'meat',
      'seafood',
      'tilapia',
      'carne',
      'pollo',
      'cerdo',
      'pavo',
      'pescado',
      'res',
      'bistec',
      'molida',
      'tocino',
      'salchicha',
      'jamon',
      'cordero',
      'camaron',
      'atun',
      'mariscos',
      'carnitas',
      'chorizo',
      'costilla',
      'chuleta',
    ],
    isDefault: true,
  },
  {
    name: 'Bakery',
    translationKey: 'bakery',
    icon: '🍞',
    color: '#FBE580',
    keywords: [
      'bread',
      'bagel',
      'muffin',
      'cake',
      'cookie',
      'donut',
      'pastry',
      'croissant',
      'roll',
      'bun',
      'tortilla',
      'pita',
      'baguette',
      'sourdough',
      'rye',
      'pan',
      'bolillo',
      'dona',
      'pastel',
      'galleta',
      'panecillo',
      'concha',
      'cuerno',
      'telera',
      'birote',
      'polvoron',
      'empanada',
      'churro',
      'rosca',
    ],
    isDefault: true,
  },
  {
    name: 'Beverages',
    translationKey: 'beverages',
    icon: '🥤',
    color: '#8B7EC8',
    keywords: [
      'water',
      'juice',
      'soda',
      'coffee',
      'tea',
      'beer',
      'wine',
      'drink',
      'cola',
      'sprite',
      'energy',
      'smoothie',
      'lemonade',
      'sparkling',
      'beverage',
      'agua',
      'jugo',
      'refresco',
      'cafe',
      'te',
      'cerveza',
      'vino',
      'bebida',
      'limonada',
      'horchata',
      'jamaica',
      'tamarindo',
      'gaseosa',
      'licuado',
    ],
    isDefault: true,
  },
  {
    name: 'Frozen',
    translationKey: 'frozen',
    icon: '🧊',
    color: '#4DB6AC',
    keywords: [
      'frozen',
      'ice cream',
      'pizza',
      'meals',
      'fries',
      'popsicle',
      'gelato',
      'sorbet',
      'frozen dinner',
      'tv dinner',
      'ice',
      'freezer',
      'congelado',
      'helado',
      'paleta',
      'papas fritas',
      'comida congelada',
      'nieve',
      'hielo',
      'pizza congelada',
    ],
    isDefault: true,
  },
  {
    name: 'Pantry',
    translationKey: 'pantry',
    icon: '🥫',
    color: '#E8976C',
    keywords: [
      'rice',
      'pasta',
      'sauce',
      'soup',
      'canned',
      'cereal',
      'flour',
      'sugar',
      'oil',
      'beans',
      'spices',
      'seasoning',
      'salt',
      'pepper',
      'vinegar',
      'honey',
      'jam',
      'peanut butter',
      'noodles',
      'oatmeal',
      'syrup',
      'arroz',
      'fideos',
      'salsa',
      'sopa',
      'enlatado',
      'cereal',
      'harina',
      'azucar',
      'aceite',
      'frijoles',
      'especias',
      'condimento',
      'sal',
      'pimienta',
      'vinagre',
      'miel',
      'mermelada',
      'crema de cacahuate',
      'avena',
      'jarabe',
      'lata',
    ],
    isDefault: true,
  },
  {
    name: 'Snacks',
    translationKey: 'snacks',
    icon: '🍿',
    color: '#F4A261',
    keywords: [
      'chips',
      'crackers',
      'popcorn',
      'candy',
      'chocolate',
      'nuts',
      'pretzels',
      'cookies',
      'granola',
      'bar',
      'trail mix',
      'gummies',
      'snack',
      'papas',
      'galletas saladas',
      'palomitas',
      'dulce',
      'dulces',
      'nueces',
      'cacahuates',
      'botana',
      'frituras',
      'chicharron',
      'gomitas',
      'chocolates',
    ],
    isDefault: true,
  },
  {
    name: 'Household',
    translationKey: 'household',
    icon: '🧹',
    color: '#8D8680',
    keywords: [
      'paper',
      'towel',
      'tissue',
      'detergent',
      'soap',
      'cleaner',
      'trash',
      'bag',
      'foil',
      'wrap',
      'sponge',
      'bleach',
      'dishwasher',
      'laundry',
      'cleaning',
      'papel',
      'toalla',
      'servilleta',
      'detergente',
      'jabon',
      'limpiador',
      'basura',
      'bolsa',
      'aluminio',
      'esponja',
      'cloro',
      'lavaplatos',
      'limpieza',
    ],
    isDefault: true,
  },
  {
    name: 'Personal Care',
    translationKey: 'personalCare',
    icon: '🧴',
    color: '#DDA0DD',
    keywords: [
      'shampoo',
      'toothpaste',
      'deodorant',
      'razor',
      'lotion',
      'soap',
      'conditioner',
      'body wash',
      'sunscreen',
      'makeup',
      'skincare',
      'hygiene',
      'dental',
      'champu',
      'pasta dental',
      'desodorante',
      'rastrillo',
      'crema',
      'jabon',
      'acondicionador',
      'gel de baño',
      'protector solar',
      'maquillaje',
      'higiene',
    ],
    isDefault: true,
  },
  {
    name: 'Other',
    translationKey: 'other',
    icon: '📦',
    color: '#A0A0A0',
    keywords: [],
    isDefault: true,
  },
];
